#:schema node_modules/wrangler/config-schema.json
name = "sublink-workers"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "222c01f8e90640208bc919278e8742cf" }
]
